.local/bin/rekeymap.sh
slstatus &
xcompmgr &
unclutter &
syncthing -no-browser &
python ~/.local/bin/keep-pres.py -s 60 -p 5 &
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
ssh-agent dwm
